"""Locked schema constants for the engine-native architecture."""

from __future__ import annotations

from enum import IntEnum

FEATURIZER_VERSION = "engine-native-featurizer-v1"

MAX_TOKENS = 40
MAX_DECK = 60
MAX_OPTIONS = 64
MAX_ORACLE = 66

LIVE_NUMERIC_WIDTH = 27
MATCH_WIDTH = 18
OPTION_NUMERIC_WIDTH = 4
DECK_ZONE_WIDTH = 4
STAT_WIDTH = 79
EFFECT_WIDTH = 130

CARD_VOCAB_SIZE = 1300
ATTACK_VOCAB_SIZE = 1600
MODEL_WIDTH = 224
N_REGISTERS = 3
TRANSFORMER_TOKENS = MAX_TOKENS + 1 + 1 + N_REGISTERS + 1

HP_CAP = 300.0
TURN_CAP = 30.0
ACTION_CAP = 20.0
ENERGY_COUNT_CAP = 5.0
TOOL_COUNT_CAP = 2.0
EVOLUTION_DEPTH_CAP = 2.0
HAND_COUNT_CAP = 12.0
DISCARD_COUNT_CAP = 30.0
DECK_COUNT_CAP = 60.0
PRIZE_COUNT_CAP = 6.0
DAMAGE_COUNTER_CAP = 20.0
REMAINING_ENERGY_CAP = 10.0
OPTION_NUMERIC_CAP = 10.0

OPT_ENTITY_NONE = -1


class Role(IntEnum):
    PAD = 0
    MY_ACTIVE = 1
    MY_BENCH = 2
    OPP_ACTIVE = 3
    OPP_BENCH = 4
    MY_HAND = 5
    DECK = 6
    GLOBAL = 7
    CLS = 8
    STADIUM = 9


class OptionKind(IntEnum):
    NUMBER = 0
    YES = 1
    NO = 2
    CARD = 3
    TOOL_CARD = 4
    ENERGY_CARD = 5
    ENERGY = 6
    PLAY = 7
    ATTACH = 8
    EVOLVE = 9
    ABILITY = 10
    DISCARD = 11
    RETREAT = 12
    ATTACK = 13
    END = 14
    SKILL = 15
    SPECIAL_CONDITION = 16


N_ROLES = len(Role)
N_OPTION_TYPES = len(OptionKind)

ENTITY_CONCEPTUAL_WIDTH = 1 + 1 + LIVE_NUMERIC_WIDTH + 1 + 1 + 1
ENTITY_CONCEPTUAL_TOTAL = MAX_TOKENS * ENTITY_CONCEPTUAL_WIDTH
DECK_CONCEPTUAL_TOTAL = MAX_DECK * (1 + DECK_ZONE_WIDTH)
OPTION_CONCEPTUAL_TOTAL = MAX_OPTIONS * (
    1 + 1 + 1 + 1 + 1 + OPTION_NUMERIC_WIDTH + 1
) + 1

assert ENTITY_CONCEPTUAL_WIDTH == 32
assert ENTITY_CONCEPTUAL_TOTAL == 1280
assert DECK_CONCEPTUAL_TOTAL == 300
assert OPTION_CONCEPTUAL_TOTAL == 641
assert TRANSFORMER_TOKENS == 46
